/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import metodos.*;
import pojos.Cliente;
import pojos.Persona;

/**
 *
 * @author Usuario
 */
public class VentanaCliente extends javax.swing.JFrame {

    DefaultTableModel modelo;

    /**
     * Creates new form Interfaz
     */
    public VentanaCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = (DefaultTableModel) tablaClientes.getModel();

        Cargar.cargaClientes(modelo);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcono = new javax.swing.JLabel();
        btnAltaCliente = new javax.swing.JButton();
        lblCorreoCli = new javax.swing.JLabel();
        entCorreoCli = new javax.swing.JTextField();
        entDireccionCli = new javax.swing.JTextField();
        lblFechaCli = new javax.swing.JLabel();
        entFechaCli = new javax.swing.JTextField();
        lblApellidoCli = new javax.swing.JLabel();
        lblNombreCli = new javax.swing.JLabel();
        lblDniCli = new javax.swing.JLabel();
        entDniCli = new javax.swing.JTextField();
        entApellidoCli = new javax.swing.JTextField();
        entNombreCli = new javax.swing.JTextField();
        lblmensaje = new javax.swing.JLabel();
        lblSueldoEmp1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnModifCli = new javax.swing.JButton();
        entTelefonoCli = new javax.swing.JTextField();
        lblDireccionCli = new javax.swing.JLabel();
        btnBajaCli = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(getIconImages());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        getContentPane().add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnAltaCliente.setText("ALTA");
        btnAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAltaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 90, 30));

        lblCorreoCli.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCorreoCli.setText("CORREO:");
        getContentPane().add(lblCorreoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));
        getContentPane().add(entCorreoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 180, 30));
        getContentPane().add(entDireccionCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 180, 30));

        lblFechaCli.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFechaCli.setText("FECHA ALTA:");
        getContentPane().add(lblFechaCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        getContentPane().add(entFechaCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 180, 30));

        lblApellidoCli.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblApellidoCli.setText("APELLIDO");
        getContentPane().add(lblApellidoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        lblNombreCli.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombreCli.setText("NOMBRE:");
        getContentPane().add(lblNombreCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        lblDniCli.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDniCli.setText("DNI:");
        getContentPane().add(lblDniCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        getContentPane().add(entDniCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 180, 30));
        getContentPane().add(entApellidoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 180, 30));
        getContentPane().add(entNombreCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 180, 30));

        lblmensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblmensaje.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lblmensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 350, 50));

        lblSueldoEmp1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSueldoEmp1.setText("TELEFONO:");
        getContentPane().add(lblSueldoEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        btnSalir.setBackground(new java.awt.Color(0, 153, 102));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(new javax.swing.border.MatteBorder(null));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, 120, 40));

        btnModifCli.setText("MODIFICAR");
        btnModifCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifCliActionPerformed(evt);
            }
        });
        getContentPane().add(btnModifCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 130, 30));
        getContentPane().add(entTelefonoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 180, 30));

        lblDireccionCli.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDireccionCli.setText("DIRECCIÓN:");
        getContentPane().add(lblDireccionCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        btnBajaCli.setText("BAJA");
        btnBajaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaCliActionPerformed(evt);
            }
        });
        getContentPane().add(btnBajaCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 90, 30));

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "NOMBRE", "APELLIDO", "FECHA", "TELEFONO", "DIRECCION", "CORREO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 650, 520));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/colormorado.PNG"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 390, 400));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaClienteActionPerformed

        String dni = entDniCli.getText().toString();
        String nombre = entNombreCli.getText().toString();
        String apellido = entApellidoCli.getText().toString();
        String direccion = entDireccionCli.getText().toString();
        String telefono = entTelefonoCli.getText();
        String fecha = entFechaCli.getText();
        String correo = entCorreoCli.getText();
        int t;

        if (!telefono.equalsIgnoreCase("")) {
            t = Integer.parseInt(telefono);
        } else {
            t = 0;
        }
        if ((correo.equalsIgnoreCase("")) | (dni.equalsIgnoreCase("")) | (nombre.equalsIgnoreCase("")) | (apellido.equalsIgnoreCase("")) | (direccion.equalsIgnoreCase("")) | (telefono.equalsIgnoreCase("")) | (fecha.equalsIgnoreCase(""))) {

            lblmensaje.setText("No se han introducido todos los datos");
        } else {
            SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
            Date fechaDate = null;
            try {
                fechaDate = formato.parse(fecha);
            } catch (ParseException ex) {
                System.out.println(ex);
            }
            System.out.println(fechaDate);
            Altas.altaCliente(fechaDate, t, direccion, correo, dni, nombre, apellido);

            lblmensaje.setText("Cliente añadido");
            entDniCli.setText("");
            entNombreCli.setText("");
            entApellidoCli.setText("");
            entFechaCli.setText("");
            entDireccionCli.setText("");
            entTelefonoCli.setText("");
            entCorreoCli.setText("");

            String[] fila = {dni, nombre, apellido, fecha, telefono, direccion, correo};

            modelo.addRow(fila);

        }


    }//GEN-LAST:event_btnAltaClienteActionPerformed

    private void btnBajaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaCliActionPerformed

        String dni = entDniCli.getText();

        Bajas.bajaCliente(dni);

        int fila = modelo.getRowCount();
        for (int i = 0; i < fila; i++) {
            modelo.removeRow(0);

        }
        Cargar.cargaClientes(modelo);

        entDniCli.setText("");
        entNombreCli.setText("");
        entFechaCli.setText("");
        entDireccionCli.setText("");
        entApellidoCli.setText("");
        entTelefonoCli.setText("");
        entCorreoCli.setText("");

        lblmensaje.setText("Se ha eliminado el Cliente\ncon DNI: " + dni);

    }//GEN-LAST:event_btnBajaCliActionPerformed

    private void btnModifCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifCliActionPerformed
        // TODO add your handling code here:
        String dni = entDniCli.getText().toString();
        String nombre = entNombreCli.getText().toString();
        String apellido = entApellidoCli.getText().toString();
        String direccion = entDireccionCli.getText().toString();
        String telefono = entTelefonoCli.getText();
        String fecha = entFechaCli.getText();
        String correo = entCorreoCli.getText();
        int t;

        if (!telefono.equalsIgnoreCase("")) {
            t = Integer.parseInt(telefono);
        } else {
            t = 0;
        }
        if ((correo.equalsIgnoreCase("")) | (dni.equalsIgnoreCase("")) | (nombre.equalsIgnoreCase("")) | (apellido.equalsIgnoreCase("")) | (direccion.equalsIgnoreCase("")) | (telefono.equalsIgnoreCase("")) | (fecha.equalsIgnoreCase(""))) {

            lblmensaje.setText("No se han introducido todos los datos");
        } else {
            SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
            Date fechaDate = null;
            try {
                fechaDate = formato.parse(fecha);
            } catch (ParseException ex) {
                System.out.println(ex);
            }
            Modificar.modificarCli(dni, nombre, apellido, direccion, t, fechaDate, correo);
            int fila = modelo.getRowCount();
            for (int i = 0; i < fila; i++) {
                modelo.removeRow(0);

            }
            Cargar.cargaClientes(modelo);
              lblmensaje.setText("Se ha modificado el cliente");
        }


    }//GEN-LAST:event_btnModifCliActionPerformed

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
        // TODO add your handling code here:

        int seleccion = tablaClientes.rowAtPoint(evt.getPoint());

        entDniCli.setText(String.valueOf(tablaClientes.getValueAt(seleccion, 0)));
        entNombreCli.setText(String.valueOf(tablaClientes.getValueAt(seleccion, 1)));
        entApellidoCli.setText(String.valueOf(tablaClientes.getValueAt(seleccion, 2)));
        entFechaCli.setText(String.valueOf(tablaClientes.getValueAt(seleccion, 3)));
        entTelefonoCli.setText(String.valueOf(tablaClientes.getValueAt(seleccion, 4)));
        entDireccionCli.setText(String.valueOf(tablaClientes.getValueAt(seleccion, 5)));
        entCorreoCli.setText(String.valueOf(tablaClientes.getValueAt(seleccion, 6)));


    }//GEN-LAST:event_tablaClientesMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        vPrincipal principal = new vPrincipal();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaCliente;
    private javax.swing.JButton btnBajaCli;
    private javax.swing.JButton btnModifCli;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField entApellidoCli;
    private javax.swing.JTextField entCorreoCli;
    private javax.swing.JTextField entDireccionCli;
    private javax.swing.JTextField entDniCli;
    private javax.swing.JTextField entFechaCli;
    private javax.swing.JTextField entNombreCli;
    private javax.swing.JTextField entTelefonoCli;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellidoCli;
    private javax.swing.JLabel lblCorreoCli;
    private javax.swing.JLabel lblDireccionCli;
    private javax.swing.JLabel lblDniCli;
    private javax.swing.JLabel lblFechaCli;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblNombreCli;
    private javax.swing.JLabel lblSueldoEmp1;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
