/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import metodos.*;

/**
 *
 * @author Usuario
 */
public class VentanaAnimal extends javax.swing.JFrame {

    DefaultTableModel modelo;

    /**
     * Creates new form Interfaz
     */
    public VentanaAnimal() {
        initComponents();
        this.setLocationRelativeTo(null);

        Cargar.cargaComboDueño(ComboBox);
        modelo = (DefaultTableModel) tablaAnimales.getModel();
        Cargar.cargaTablaAnimales(modelo);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcono = new javax.swing.JLabel();
        btnAltaAnimal = new javax.swing.JButton();
        lblpreciolibro = new javax.swing.JLabel();
        lblnombrelibro1 = new javax.swing.JLabel();
        entAlimentacionAni = new javax.swing.JTextField();
        lblnombrelibro2 = new javax.swing.JLabel();
        lblnombrelibro3 = new javax.swing.JLabel();
        btnBajaAnimal = new javax.swing.JButton();
        btnModifAnimal = new javax.swing.JButton();
        lblpreciolibro1 = new javax.swing.JLabel();
        entREIAC = new javax.swing.JTextField();
        entTipoAni = new javax.swing.JTextField();
        entNombreAni = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        lblmensaje = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAnimales = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(getIconImages());
        setMinimumSize(new java.awt.Dimension(930, 620));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        getContentPane().add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnAltaAnimal.setText("ALTA");
        btnAltaAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaAnimalActionPerformed(evt);
            }
        });
        getContentPane().add(btnAltaAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 90, 30));

        lblpreciolibro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblpreciolibro.setText("DNI Dueño:");
        getContentPane().add(lblpreciolibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        lblnombrelibro1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnombrelibro1.setText("Alimentacion:");
        getContentPane().add(lblnombrelibro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));
        getContentPane().add(entAlimentacionAni, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 180, 30));

        lblnombrelibro2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnombrelibro2.setText("Tipo:");
        getContentPane().add(lblnombrelibro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        lblnombrelibro3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnombrelibro3.setText("Nombre: ");
        getContentPane().add(lblnombrelibro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        btnBajaAnimal.setText("BAJA");
        btnBajaAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaAnimalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBajaAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 90, 30));

        btnModifAnimal.setText("MODIFICAR");
        btnModifAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifAnimalActionPerformed(evt);
            }
        });
        getContentPane().add(btnModifAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 120, 30));

        lblpreciolibro1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblpreciolibro1.setText("REIAC:");
        getContentPane().add(lblpreciolibro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        getContentPane().add(entREIAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 180, 30));
        getContentPane().add(entTipoAni, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 180, 30));
        getContentPane().add(entNombreAni, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 180, 30));

        btnSalir.setBackground(new java.awt.Color(0, 153, 102));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(new javax.swing.border.MatteBorder(null));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, 120, 40));

        lblmensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblmensaje.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lblmensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 300, 50));

        getContentPane().add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 180, 30));

        tablaAnimales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REIAC", "NOMBRE", "TIPO", "ALIMENTACION", "DUEÑO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAnimalesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAnimales);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 510, 470));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/colormorado.PNG"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 390, 390));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaAnimalActionPerformed

        String reiac = entREIAC.getText().toString();
        String nombre = entNombreAni.getText().toString();
        String tipo = entTipoAni.getText().toString();
        String alimentacion = entAlimentacionAni.getText().toString();
        String dni = (String) ComboBox.getSelectedItem();
        System.out.println(dni);

        if ((reiac.equalsIgnoreCase("") | (nombre.equalsIgnoreCase("") | (tipo.equalsIgnoreCase("") | (dni.equalsIgnoreCase("")) | (alimentacion.equalsIgnoreCase("")))))) {

            lblmensaje.setText("No se han introducido todos los datos");
        } else {
            Altas.altaAnimal(reiac, nombre, tipo, alimentacion, dni);
            lblmensaje.setText("Animal añadido");
            entREIAC.setText("");
            entNombreAni.setText("");
            entTipoAni.setText("");
            entAlimentacionAni.setText("");

            String[] fila = {reiac, nombre, tipo, alimentacion, dni};

            modelo.addRow(fila);

        }


    }//GEN-LAST:event_btnAltaAnimalActionPerformed

    private void btnBajaAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaAnimalActionPerformed

        String reiac = entREIAC.getText();

        Bajas.bajaAnimal(reiac);

        int fila = modelo.getRowCount();
        for (int i = 0; i < fila; i++) {
            modelo.removeRow(0);

        }
        Cargar.cargaTablaAnimales(modelo);

        entNombreAni.setText("");
        entREIAC.setText("");
        entTipoAni.setText("");
        lblmensaje.setText("Se ha eliminado el animnal\ncon REIAC: " + reiac);

    }//GEN-LAST:event_btnBajaAnimalActionPerformed

    private void btnModifAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifAnimalActionPerformed
        // TODO add your handling code here:

        String reiac = entREIAC.getText().toString();
        String nombre = entNombreAni.getText().toString();
        String tipo = entTipoAni.getText().toString();
        String alimentacion = entAlimentacionAni.getText().toString();
        String dni = (String) ComboBox.getSelectedItem();
        System.out.println(dni);

        if ((reiac.equalsIgnoreCase("") | (nombre.equalsIgnoreCase("") | (tipo.equalsIgnoreCase("") | (dni.equalsIgnoreCase("")) | (alimentacion.equalsIgnoreCase("")))))) {

            lblmensaje.setText("No se han introducido todos los datos");
        } else {

            Modificar.modificarAnimal(reiac, nombre, tipo, alimentacion, dni);

            int fila = modelo.getRowCount();
            for (int i = 0; i < fila; i++) {
                modelo.removeRow(0);

            }
            Cargar.cargaTablaAnimales(modelo);
  lblmensaje.setText("Se ha modificado el animal");
        }

    }//GEN-LAST:event_btnModifAnimalActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        vPrincipal ventana = new vPrincipal();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tablaAnimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAnimalesMouseClicked
        // TODO add your handling code here:
        int seleccion = tablaAnimales.rowAtPoint(evt.getPoint());

        entREIAC.setText(String.valueOf(tablaAnimales.getValueAt(seleccion, 0)));
        entNombreAni.setText(String.valueOf(tablaAnimales.getValueAt(seleccion, 1)));
        entTipoAni.setText(String.valueOf(tablaAnimales.getValueAt(seleccion, 2)));
        entAlimentacionAni.setText(String.valueOf(tablaAnimales.getValueAt(seleccion, 3)));
        ComboBox.setSelectedItem(String.valueOf(tablaAnimales.getValueAt(seleccion, 4)));
    }//GEN-LAST:event_tablaAnimalesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton btnAltaAnimal;
    private javax.swing.JButton btnBajaAnimal;
    private javax.swing.JButton btnModifAnimal;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField entAlimentacionAni;
    private javax.swing.JTextField entNombreAni;
    private javax.swing.JTextField entREIAC;
    private javax.swing.JTextField entTipoAni;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JLabel lblnombrelibro1;
    private javax.swing.JLabel lblnombrelibro2;
    private javax.swing.JLabel lblnombrelibro3;
    private javax.swing.JLabel lblpreciolibro;
    private javax.swing.JLabel lblpreciolibro1;
    private javax.swing.JTable tablaAnimales;
    // End of variables declaration//GEN-END:variables
}
